# Generated by Django 3.1 on 2020-10-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200920_1837'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('log_schedule_id', models.AutoField(primary_key=True, serialize=False)),
                ('lecture_link', models.CharField(default=None, max_length=100)),
                ('tutor_link', models.CharField(default=None, max_length=100)),
                ('slack_user_id', models.CharField(max_length=100, null=True)),
            ],
            options={
                'db_table': 'log_schedule',
                'unique_together': {('slack_user_id', 'log_schedule_id')},
            },
        ),
    ]
